install:
  sheldon:
    marlonrichert/zsh-autocomplete: 23.05.24
    Tarrasch/zsh-bd: d4a55e6
    sindresorhus/pure: fpath path source PATH v1.21.0
    # zsh-users/zsh-syntax-highlighting:
    zdharma-continuum/fast-syntax-highlighting: 13d7b4e
    # https://github.com/wfxr/forgit
    # olets/zsh-abbr: fpath source v5.1.0
    # z-shell/zsh-lsd: v1.0.0
    Dbz/kube-aliases:
    # MenkeTechnologies/zsh-expand:
    greymd/docker-zsh-completion:
  brew:
    - autojump
    - docker-compose
    - fzf
    - how2terminal/how2/how2
    - jdtls
    - jq
    - k9s
    - ncdu
    - neovim
    - nvm
    - pipx
    - poppler
    - ranger
    - ripgrep
    - ruby
    - sheldon
    - yq
    - zsh
    - lazydocker
    - wget
    - txn2/tap/kubefwd
    - kubectx
    # - multipass
    - helm
    - diff-so-fancy
    - eza
    # - karabiner-elements
    - ondir
    - python-lsp-server
    - mise
    - sops
    - age
    - maccy
    - font-hack-nerd-font
    - jstkdng/programs/ueberzugpp
    - hammerspoon
    - mutagen-io/mutagen/mutagen
  mise:
    - java@temurin-11
    - java@temurin-17
    - python@3.11
    - python@3.12
    - node@22
  npm:
    - "@mermaid-js/mermaid-cli"
